In [42]:
# Importing numpy
import numpy as np
# Creating 2 dimensional array
array1=np.arange(12).reshape(4,3)
print("Array is:")
print(array1)
print("Dimensions of array is:",np.ndim(array1))
print("Shape of array is:",np.shape(array1))

Array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Dimensions of array is: 2
Shape of array is: (4, 3)


In [7]:
# Indexing in array
# Starts from 0
# First index is for row second is for column
print("Element at 4 row 2 column is:",array1[3][1])

Element at 4 row 2 column is: 10


In [41]:
# Creating 2 dimensional array
a2=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print("Array is:")
print(a2)
print("Dimensions of array is:",np.ndim(a2))
print("Shape of array is:",np.shape(a2))

Array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions of array is: 2
Shape of array is: (3, 3)


In [8]:
# Indexing in array
# Starts from 0
# First index is for row second is for column
print("Element at 3 row 2 column is:",a2[2,1])

Element at 3 row 2 column is: 8


In [40]:
# Creating 3 dimensional array using arange function
# arange gives number starting from a given range
# 3 parameters start,stop,step
# reshape reshapes array into required shape
array1=np.arange(18).reshape(3,2,3)
print("Array using arange and reshape function is:")
print(array1)
print("Dimensions of array is:",np.ndim(array1))
print("Shape of array is:",np.shape(array1))

Array using arange and reshape function is:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
Dimensions of array is: 3
Shape of array is: (3, 2, 3)


In [11]:
# Indexing in array
# Starts from 0
# First index is for outer layer second is for row and third is for column
print("Element at 3 layer 1 row 2 column is:",array1[2][0][1])

Element at 3 layer 1 row 2 column is: 13


In [37]:
# Creating 3 dimensional array
arr3d=np.array([[[1,2,3],[4,5,6]],[[14,15,16],[7,8,9]]])
print("Array using array function is:")
print(arr3d)
print("Dimensions of array is:",np.ndim(arr3d))
print("Shape of array is:",np.shape(arr3d))

Array using array function is:
[[[ 1  2  3]
  [ 4  5  6]]

 [[14 15 16]
  [ 7  8  9]]]
Dimensions of array is: 3
Shape of array is: (2, 2, 3)


In [24]:
# Indexing in array
# Starts from 0
# First index is for outer layer second is for row and third is for column
print("First Layer is:")
print(arr3d[0])
print("Elements at 2 layer is:")
print(arr3d[1])
print("Elements at 2 layer 1 row is:",arr3d[1,0])

First Layer is:
[[1 2 3]
 [4 5 6]]
Elements at 2 layer is:
[[14 15 16]
 [ 7  8  9]]
Elements at 2 layer 1 row is: [14 15 16]


In [26]:
# Creating 3 dimensional array
x=np.array([[[1,2,3],[4,5,6]],[[14,15,16],[7,8,9]]])
print("Array using array function is:")
print(x)
# Conditional Formatting in array-selecting elements that satisfy a particular condition
print("Number greater than 5 are:")
print(x[x>5])
print("Number equal to 4 are:")
print(x[x==4])
print("Number lesser than 5 are:")
print(x[x<5])

Array using array function is:
[[[ 1  2  3]
  [ 4  5  6]]

 [[14 15 16]
  [ 7  8  9]]]
Number greater than 5 are:
[ 6 14 15 16  7  8  9]
Number equal to 4 are:
[4]
Number lesser than 5 are:
[1 2 3 4]


In [27]:
# Creating 1 dimensional complex number array
a=np.array([1,2+6j,5,3+5j,10,50])
print("Array is:")
print(a)
# Printing complex number in array
print("Complex number in array are:",a[np.iscomplex(a)])

Array is:
[ 1.+0.j  2.+6.j  5.+0.j  3.+5.j 10.+0.j 50.+0.j]
Complex number in array are: [2.+6.j 3.+5.j]


In [29]:
# Creating 3 dimensional array
a=np.array([[[1,2,3],[4,5,6]],[[14,15,16],[7,8,9]]])
print("Array is:")
print(a)
# Conditional Formatting in array-selecting elements that satisfy a particular condition
print("Square of number divisible by 4 are:",a[a%4==0]**2)

Array is:
[[[ 1  2  3]
  [ 4  5  6]]

 [[14 15 16]
  [ 7  8  9]]]
Square of number divisible by 4 are: [ 16 256  64]


In [43]:
# Creating 3 dimensional array
a = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]], [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",np.shape(a))

Array is:
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]]
Dimensions of array is: 4
Shape of array is: (4, 3, 2, 3)


In [47]:
a1 = np.array([[[1,2,3],[4,5,6]],7,8,9,[10,11,12],[[13,14,15],[16,17,18],[19,20,21]]])
print("Array is:")
print(a1)
print("Dimensions of array is:",np.ndim(a1))
print("Shape of array is:",np.shape(a1))

Array is:
[list([[1, 2, 3], [4, 5, 6]]) 7 8 9 list([10, 11, 12])
 list([[13, 14, 15], [16, 17, 18], [19, 20, 21]])]
Dimensions of array is: 1
Shape of array is: (6,)


<ipython-input-47-99f822ac6765>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = np.array([[[1,2,3],[4,5,6]],7,8,9,[10,11,12],[[13,14,15],[16,17,18],[19,20,21]]])


In [48]:
# Creating array and setting dimensions using ndmin
a=np.array([1,2,3,4],ndmin=4)
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",np.shape(a))

Array is:
[[[[1 2 3 4]]]]
Dimensions of array is: 4
Shape of array is: (1, 1, 1, 4)


In [50]:
# Creating list
a=[12,'nm',90,'bh']
print("List is:",a)
# Checking type of list
print("Type is:",type(a))

List is: [12, 'nm', 90, 'bh']
Type is: <class 'list'>


In [51]:
# Converting to array
a=np.array(a)
print("Array is:",a)
# Checking type of array
print("Type is:",type(a))

Array is: ['12' 'nm' '90' 'bh']
Type is: <class 'numpy.ndarray'>


In [52]:
# Creating Lists
b=[13, 67, 90]
c=[13, 67, 90]
d=[13, 67, 90]
# Combining lists
a=[b,c,d]
# Converting to array
l=np.array(a)
print("Array is:")
print(l)
print("Dimensions of array is:",np.ndim(l))
print("Shape of array is:",np.shape(l))

Array is:
[[13 67 90]
 [13 67 90]
 [13 67 90]]
Dimensions of array is: 2
Shape of array is: (3, 3)


In [65]:
# numpy array functions
# Creating array
a=np.array(42)
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
42
Dimensions of array is: 0
Shape of array is: ()
Size of array is: 1


In [66]:
# numpy array functions
# Creating array
a=np.array([42])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[42]
Dimensions of array is: 1
Shape of array is: (1,)
Size of array is: 1


In [67]:
# Creating array
a=np.array([42,])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[42]
Dimensions of array is: 1
Shape of array is: (1,)
Size of array is: 1


In [68]:
# Creating array
a=np.array([42,90,78,65,54])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[42 90 78 65 54]
Dimensions of array is: 1
Shape of array is: (5,)
Size of array is: 5


In [69]:
# Creating array
a=np.array([[42,90,78,65,54],[9,7,8,6,43]])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[[42 90 78 65 54]
 [ 9  7  8  6 43]]
Dimensions of array is: 2
Shape of array is: (2, 5)
Size of array is: 10


In [73]:
# Creating array
a=np.array([[[42,90,78,65,54],[9,7,8,6,43]],[[12,34,45,67,78,98],[1,2,3,4,5]]])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[[list([42, 90, 78, 65, 54]) list([9, 7, 8, 6, 43])]
 [list([12, 34, 45, 67, 78, 98]) list([1, 2, 3, 4, 5])]]
Dimensions of array is: 2
Shape of array is: (2, 2)
Size of array is: 4


<ipython-input-73-0b5e660214ad>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[[42,90,78,65,54],[9,7,8,6,43]],[[12,34,45,67,78,98],[1,2,3,4,5]]])


In [72]:
# Creating array using ones function
# Create array of ones
a=np.ones([2,2])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[[1. 1.]
 [1. 1.]]
Dimensions of array is: 2
Shape of array is: (2, 2)
Size of array is: 4


In [75]:
# Creating array using ones_like function
# Replaces ones to an array
a=np.ones_like([2,2,4,5,6,7,8])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[1 1 1 1 1 1 1]
Dimensions of array is: 1
Shape of array is: (7,)
Size of array is: 7


In [78]:
# Creating array using zeroes_like function
# Create array of zeros
a=np.zeros([2,2])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[[0. 0.]
 [0. 0.]]
Dimensions of array is: 2
Shape of array is: (2, 2)
Size of array is: 4


In [79]:
# Creating array using zeroes_like function
# Replaces zeros to an array
a=np.zeros_like([2,2,4,5,6,7,8])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[0 0 0 0 0 0 0]
Dimensions of array is: 1
Shape of array is: (7,)
Size of array is: 7


In [81]:
# Creating array using full function
# Creates array using the given value
a=np.full([2,2],67)
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[[67 67]
 [67 67]]
Dimensions of array is: 2
Shape of array is: (2, 2)
Size of array is: 4


In [82]:
# Creating array using full_like function
# Replaces array using the given value
a=np.full_like([2,2,89,7,6,5,12,3,4],67)
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[67 67 67 67 67 67 67 67 67]
Dimensions of array is: 1
Shape of array is: (9,)
Size of array is: 9


In [83]:
# Giving dtype to arange and creating an array
print("Array is:")
print(np.arange(10,dtype=float).reshape(2,5))

Array is:
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [87]:
# np.empty function is used to create empty arrays in which values will be filled later
a= np.empty([3,4])
print("Array is:")
print(a)
print("Dimensions of array is:",np.ndim(a))
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)

Array is:
[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 6.9e-323 7.4e-323]
 [7.9e-323 3.5e-323 4.0e-323 4.4e-323]]
Dimensions of array is: 2
Shape of array is: (3, 4)
Size of array is: 12


In [93]:
# Mathematical Functions in numpy arrays
# Creating two arrays
arr1=np.array([10,11,23,45])
print("Array 1 is:",arr1)
arr2=np.array([20,11,23,95])
print("Array 2 is:",arr2)
# Creating new array by Adding two arrays
newarr=np.add(arr1,arr2)
print("Addition of Array is:",newarr)
# Creating new array by Subtracting two arrays
new=np.subtract(arr1,arr2)
print("Subtraction of Array is:",new)
print("Multiplication of Array is:",np.multiply(arr1,arr2))
print("Division of Array using mod function is:",np.mod(arr1,arr2))
print("Division of Array using remainder function is:",np.remainder(arr1,arr2))

Array 1 is: [10 11 23 45]
Array 2 is: [20 11 23 95]
Addition of Array is: [ 30  22  46 140]
Subtraction of Array is: [-10   0   0 -50]
Multiplication of Array is: [ 200  121  529 4275]
Division of Array using mod function is: [10  0  0 45]
Division of Array using remainder function is: [10  0  0 45]


In [94]:
# Directly doing mathematical computation without functions
# Creating two arrays
arr1=np.array([10,11,23,45])
print("Array 1 is:",arr1)
arr2=np.array([20,11,23,95])
print("Array 2 is:",arr2)
# Creating new array by Adding two arrays
newarr=arr1+arr2
print("Addition of Array is:",newarr)
# Creating new array by Subtracting two arrays
new=arr1-arr2
print("Subtraction of Array is:",new)
print("Multiplication of Array is:",arr1*arr2)
print("Division of Array using mod function is:",arr1/arr2)

Array 1 is: [10 11 23 45]
Array 2 is: [20 11 23 95]
Addition of Array is: [ 30  22  46 140]
Subtraction of Array is: [-10   0   0 -50]
Multiplication of Array is: [ 200  121  529 4275]
Division of Array using mod function is: [0.5        1.         1.         0.47368421]


In [98]:
# Other Functions
print("Array is:",arr1)
print("Maximum element is:",np.max(arr1))
print("Minimum element is:",np.min(arr1))
print("Median is:",np.median(arr1))
print("Mean is:",np.mean(arr1))
print("Average is:",np.average(arr1))
print("Percentile is:",np.percentile(arr1,11))
print("Standard Deviation is:",np.std(arr1))
print("Variance is:",np.var(arr1))

Array is: [10 11 23 45]
Maximum element is: 45
Minimum element is: 10
Median is: 17.0
Mean is: 22.25
Average is: 22.25
Percentile is: 10.33
Standard Deviation is: 14.095655359010449
Variance is: 198.6875


In [101]:
# Creating  two arrays
even=np.array([0,2,4,6,8,10,14,16])
print("Even Array is:",even)
odd=even+1
print("Odd Array is:",odd)
print("Bitwise and of two arrays")
print(np.bitwise_and(even,odd))
print("Bitwise or of two arrays")
print(np.bitwise_or(even,odd))
print("Bitwise xor of two arrays")
print(np.bitwise_xor(even,odd))

Even Array is: [ 0  2  4  6  8 10 14 16]
Odd Array is: [ 1  3  5  7  9 11 15 17]
Bitwise and of two arrays
[ 0  2  4  6  8 10 14 16]
Bitwise or of two arrays
[ 1  3  5  7  9 11 15 17]
Bitwise xor of two arrays
[1 1 1 1 1 1 1 1]


In [102]:
print("Bitwise or of two arrays")
print(np.bitwise_or(even,odd))
print("Bitwise xor of two arrays")
print(np.invert(even,odd))

Bitwise or of two arrays
[ 1  3  5  7  9 11 15 17]
Bitwise xor of two arrays
[ -1  -3  -5  -7  -9 -11 -15 -17]


In [106]:
# Creating array
array=np.array([10,11,23,45,11,23,45,66,33,12,112,90,98,76])
# Sorting
array.sort() # array.sort()-Dosen't return anything,saves value in actual array
print("Sorted array is:",array)
# Reverse Sorting
array[::-1].sort() #-Dosen't return anything,saves value in actual array
print("Reversed Sorted array is:",array)

Sorted array is: [ 10  11  11  12  23  23  33  45  45  66  76  90  98 112]
Reversed Sorted array is: [112  98  90  76  66  45  45  33  23  23  12  11  11  10]


In [107]:
# numpy sorting function
# np.sort(array)-Returns sorted array
print("Sorted array using numpy sort function is:",np.sort(array))

Sorted array using numpy sort function is: [ 10  11  11  12  23  23  33  45  45  66  76  90  98 112]


In [109]:
# Creating an array
arr1=np.array([[11,2,13,4,5,26],[35,5,15,10,20,90]])
print("Array is:")
print(arr1)
# numpy sorting function with axis
print("Sorting with axis None:")
print(np.sort(arr1,axis=None))
print("Sorting with axis 0:")
print(np.sort(arr1,axis=0))
print("Sorting with axis 1:")
print(np.sort(arr1,axis=1))

Array is:
[[11  2 13  4  5 26]
 [35  5 15 10 20 90]]
Sorting with axis None:
[ 2  4  5  5 10 11 13 15 20 26 35 90]
Sorting with axis 0:
[[11  2 13  4  5 26]
 [35  5 15 10 20 90]]
Sorting with axis 1:
[[ 2  4  5 11 13 26]
 [ 5 10 15 20 35 90]]


In [110]:
# Giving types in sort
a=np.array([1,5,6,7,3,4])
print("Array is:")
print(a)
print("Sorting using Heap sort",np.sort(a,kind='heapsort'))
print("Sorting using Merge sort",np.sort(a,kind='mergesort'))
print("Sorting using Quick sort",np.sort(a,kind='quicksort'))
print("Sorting using Selection sort",np.sort(a,kind='selectionsort'))

Array is:
[1 5 6 7 3 4]
Sorting using Heap sort [1 3 4 5 6 7]
Sorting using Merge sort [1 3 4 5 6 7]
Sorting using Quick sort [1 3 4 5 6 7]
Sorting using Selection sort [1 3 4 5 6 7]
