Importing numpy

In [1]:
import numpy as np

Creating an aray in numpy

In [2]:
arr=np.array([1,2,4,5,6,7])
print("Array is:")
print(arr)
print("Type is:",type(arr))
print("Dimension is:",arr.ndim)
print("Shape is:",arr.shape)
print("Max element is:",arr.max())
print("Min element is:",arr.min())

Array is:
[1 2 4 5 6 7]
Type is: <class 'numpy.ndarray'>
Dimension is: 1
Shape is: (6,)
Max element is: 7
Min element is: 1


Creating an aray in numpy

In [3]:
arr=np.array([[1,2],[4,5],[6,7]])
print("Array is:")
print(arr)
print("Type is:",type(arr))
print("Dimension is:",arr.ndim)
print("Shape is:",arr.shape)
print("Max element is:",arr.max())
print("Min element is:",arr.min())

Array is:
[[1 2]
 [4 5]
 [6 7]]
Type is: <class 'numpy.ndarray'>
Dimension is: 2
Shape is: (3, 2)
Max element is: 7
Min element is: 1


Creating an aray in numpy

In [4]:
arr=np.array([[[1,2],[4,5],[6,7]]])
print("Array is:")
print(arr)
print("Type is:",type(arr))
print("Dimension is:",arr.ndim)
print("Shape is:",arr.shape)
print("Max element is:",arr.max())
print("Min element is:",arr.min())

Array is:
[[[1 2]
  [4 5]
  [6 7]]]
Type is: <class 'numpy.ndarray'>
Dimension is: 3
Shape is: (1, 3, 2)
Max element is: 7
Min element is: 1


In [5]:
arr=np.array([[[1,2]]])
print("Array is:")
print(arr)
print("Type is:",type(arr))
print("Dimension is:",arr.ndim)
print("Shape is:",arr.shape)
print("Max element is:",arr.max())
print("Min element is:",arr.min())

Array is:
[[[1 2]]]
Type is: <class 'numpy.ndarray'>
Dimension is: 3
Shape is: (1, 1, 2)
Max element is: 2
Min element is: 1


(3,4,2,2)

In [6]:
arr_d = np.array([
    [[[1,2], [1,2]], [[1,2], [1,2]], [[1,2], [1,2]], [[1,2], [1,2]]], [[[1,2], [1,2]], [[1,2], [1,2]], [[1,2], [1,2]], [[1,2], [1,2]]], [[[1,2], [1,2]], [[1,2], [1,2]], [[1,2], [1,2]], [[1,2], [1,2]]]
])
print("Array is:")
print(arr_d)
print("Dimension of Array is: ",arr_d.ndim)
print("Shape is:",arr_d.shape)

Array is:
[[[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]


 [[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]


 [[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]]
Dimension of Array is:  4
Shape is: (3, 4, 2, 2)


In [7]:
ar=np.arange(1,49)
ar=ar.reshape(3,4,2,2)
print("Array is: ",ar)
print(ar.shape)

Array is:  [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[17 18]
   [19 20]]

  [[21 22]
   [23 24]]

  [[25 26]
   [27 28]]

  [[29 30]
   [31 32]]]


 [[[33 34]
   [35 36]]

  [[37 38]
   [39 40]]

  [[41 42]
   [43 44]]

  [[45 46]
   [47 48]]]]
(3, 4, 2, 2)


arange creates array of required range

In [8]:
arr1=np.arange(10)
print("Array created in a particular range using arange function is:")
print(arr1)
print("Type is:",type(arr1))
print("Dimension is:",arr1.ndim)
print("Shape is:",arr1.shape)
print("Max element is:",arr1.max())
print("Min element is:",arr1.min())

Array created in a particular range using arange function is:
[0 1 2 3 4 5 6 7 8 9]
Type is: <class 'numpy.ndarray'>
Dimension is: 1
Shape is: (10,)
Max element is: 9
Min element is: 0


To increase dimensions we can add 1

In [9]:
arr2=np.arange(10)
arr2=arr2.reshape(5,1,2)
print("Array created in a particular range using arange function and reshape function is:")
print(arr2)
print("Type is:",type(arr2))
print("Dimension is:",arr2.ndim)
print("Shape is:",arr2.shape)
print("Max element is:",arr2.max())
print("Min element is:",arr2.min())

Array created in a particular range using arange function and reshape function is:
[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]

 [[8 9]]]
Type is: <class 'numpy.ndarray'>
Dimension is: 3
Shape is: (5, 1, 2)
Max element is: 9
Min element is: 0


fill is used to fill one value to all array

In [10]:
arr1.fill(7)
print("Array filled by using fill function for 7  is:")
print(arr1)

Array filled by using fill function for 7  is:
[7 7 7 7 7 7 7 7 7 7]


In [11]:
arr2=np.full((3,4,2),6,dtype=float)
print("Array filled by using full function for 6  is:")
print(arr2)

Array filled by using full function for 6  is:
[[[6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]
  [6. 6.]
  [6. 6.]]]


zeros is used to fill array with zeros,by default data type is float

In [12]:
zero=np.zeros((5,3),dtype=int)
print("Array filled with zero is:")
print(zero)

Array filled with zero is:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


ones is used to fill array with ones ,by default data type is float

In [13]:
ones=np.ones((5,3),dtype=int)
print("Array filled with ones is:")
print(ones)

Array filled with ones is:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


For identity matrix<br>
If we give one value it will create square matrix else specified number of rows and columns

In [14]:
eye=np.eye(4,5,1)
print("Identity Matrix is:")
print(eye)

Identity Matrix is:
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


axis is used to decide if we fill data row wise or column wise

In [15]:
print(np.append(eye,np.arange(20).reshape((4,5)),axis=1))

[[ 0.  1.  0.  0.  0.  0.  1.  2.  3.  4.]
 [ 0.  0.  1.  0.  0.  5.  6.  7.  8.  9.]
 [ 0.  0.  0.  1.  0. 10. 11. 12. 13. 14.]
 [ 0.  0.  0.  0.  1. 15. 16. 17. 18. 19.]]


Data is needed to be in the same dimensions to match<br>
print(np.append(eye,np.arange(15).reshape((3,5)),axis=1)) - gives error

In [16]:
eye=np.concatenate((eye,np.arange(20).reshape((4,5)),np.arange(20).reshape((4,5)),np.arange(20).reshape((4,5))),axis=1)
print("Identity Matrix after concatenation is:")
print(eye)

Identity Matrix after concatenation is:
[[ 0.  1.  0.  0.  0.  0.  1.  2.  3.  4.  0.  1.  2.  3.  4.  0.  1.  2.
   3.  4.]
 [ 0.  0.  1.  0.  0.  5.  6.  7.  8.  9.  5.  6.  7.  8.  9.  5.  6.  7.
   8.  9.]
 [ 0.  0.  0.  1.  0. 10. 11. 12. 13. 14. 10. 11. 12. 13. 14. 10. 11. 12.
  13. 14.]
 [ 0.  0.  0.  0.  1. 15. 16. 17. 18. 19. 15. 16. 17. 18. 19. 15. 16. 17.
  18. 19.]]


Gives information about array<br>
The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis.

In [17]:
print("Information is:")
print(np.info(eye))

Information is:
class:  ndarray
shape:  (4, 20)
strides:  (160, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x21b3ec029d0
byteorder:  little
byteswap:  False
type: float64
None


For Matrix Multiplication<br>
10 * [[1,2]  [[6,7]<br>
      [3,4]]  [8,9]]

In [18]:
out=10 * np.dot(np.array([[1,2],[3,4]]),np.array([[6,7],[8,9]]))
print("Matrix Multiplication is:")
print(out)

Matrix Multiplication is:
[[220 250]
 [500 570]]


How to make this multiplication work<br>
we can use transpose

In [19]:
out1=10 * np.dot(np.array([[6,7],[8,9]]),np.array([[1,2],[3,4],[5,6]]).T)
print("Matrix Multiplication is:")
print(out1)
print(np.std(out))
# To get information about a function
help(np.array)
# To save data
np.savetxt("data.txt",out,delimiter=",")
out1=np.loadtxt("data.txt",delimiter=',')
print(out1)

Matrix Multiplication is:
[[200 460 720]
 [260 600 940]]
152.3975065412817
Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optiona

In [20]:
random_arr=np.random.random(10)
print(random_arr)
print(np.random.randint(5,20,10))
'''
Ask the user to enter a number:5
1 2 3 4 5
5 6 7 8 9
2 4 6 8 9
1 2 3 4 5
5 6 7 8 9
(5,5)
'''

[0.27899717 0.43547113 0.21874408 0.52215446 0.97774112 0.47466369
 0.71565226 0.77914533 0.11393341 0.44680394]
[18 13 12  7 15 19 11  7 12  8]


'\nAsk the user to enter a number:5\n1 2 3 4 5\n5 6 7 8 9\n2 4 6 8 9\n1 2 3 4 5\n5 6 7 8 9\n(5,5)\n'

Directly taking input without specifying condition

In [21]:
array=[]
for x in range(int(input("Enter number of rows and columns: "))):
    out=[int(j) for j in input().split()]
    array.append(out)
else:
    array=np.array(array)
    print("Array is:")
    print(array)
    print("Shape of Array is:",array.shape)

Enter number of rows and columns: 5
1 2 3 4 5
5 6 4 7 8
4 5 6 8 9
4 1 2 3 5
1 5 2 7 8
Array is:
[[1 2 3 4 5]
 [5 6 4 7 8]
 [4 5 6 8 9]
 [4 1 2 3 5]
 [1 5 2 7 8]]
Shape of Array is: (5, 5)


Directly taking input specifying condition for no of elements as input in rows

In [22]:
array=[]
for x in range(int(input("Enter number of rows and columns:"))):
    out=[int(j) for j in input().split()][:5]
    if len(out)<5:
        print("Enter 5 values: ")
        out = [int(j) for j in input().split()][:5]
    array.append(out)
else:
    array=np.array(array)
    print("Array is:")
    print(array)
    print("Shape of Array is:", array.shape)

Enter number of rows and columns:5
1 2 3 4 5
5 6 8 9 7
4 5 6 5 8
1 4 5 2 3
4 5 8 7 9
Array is:
[[1 2 3 4 5]
 [5 6 8 9 7]
 [4 5 6 5 8]
 [1 4 5 2 3]
 [4 5 8 7 9]]
Shape of Array is: (5, 5)
